enum fuel_types {
    petrol
    diesel
    electric
    hybrid
}

enum transmission_types {
    manual
    automatic
    "semi-automatic"
}

TABLE customer {
    customer_id INTERGER [primary key]
    first_name VARCHAR
    last_name VARCHAR
    town_name VARCHAR
    county_id INTEGER [ref: > counties.county_id]
}

TABLE counties {
    county_id INTEGER [primary key]
    county_name VARCHAR
}

TABLE makes {
    make_id INTEGER [primary key]
    make_name VARCHAR
}

TABLE models {
    model_id INTEGER [primary key]
    model_name VARCHAR
    make_id INTEGER [ref: > makes.make_id]
}

TABLE colours {
    colour_id INTEGER [primary key]
    colour_name VARCHAR
}


/* Cars for sale table */
TABLE cars_for_sale {
    car_id INTEGER [primary key]
    model_id INTEGER            [ref: > models.model_id]
    colour_id INTEGER           [ref: > colours.colour_id]
    fuel_type fuel_types
    transmission_type transmission_types
    customer_id INTEGER         [ref: > customer.customer_id]
    year INTEGER
    price FLOAT
    mileage INTEGER
    description TEXT
}